### ISSUE TITLE
App crash when i put email on Get Started page

### ISSUE THREAD

**Issue by msubham193** [fossasia/open-event-organizer-android#2204]
When i open the app  put email for signup and click get started and then in toast message it shows error
![IMG_20210105_102417 1](https://user-images.githubusercontent.com/63531369/103608128-9fa7af00-4f40-11eb-92f9-0c0e177f3a61.jpg)

**Comment by prateek-singh-3212** [comment]
@msubham193 are you working on this issue?

**Comment by msubham193** [comment]
@prateek-singh-3212  No.....

**Comment by iamvs-2002** [comment]
May I try to resolve this issue, please?

**Comment by iamvs-2002** [comment]
> @iamvs-2002 yes Plz go-ahead

Alright, I'll begin to work on this issue. Thank you!

**Comment by iamvs-2002** [comment]
> @iamvs-2002 yes Plz go ahead

Hey! I was going through the code, I have got the solution to avoid this error.
I have solved the email issue, it was just a little error in the models as the getter and setter methods were not defined there.

But now, I am stuck in some other issue which is: DaggerAppComponent not created!
I checked the dependencies, all correct!
I tried to clean and rebuild the project, but still the DaggerAppComponent is not found!
Kindly help me with this error as due to it, I am unable to run the app.
